title: DCIEM Decompression Model (1973)
description: Fortran IV transcription of the 1973 DCIEM digital decompression programs
remote_theme: pages-themes/cayman@v0.2.0

math: mathjax

url: ""
baseurl: "/DCIEM"

exclude:
  - Gemfile
  - Gemfile.lock
  - "Digital computation of decompression profiles.pdf"
